# Generated by Django 4.1.4 on 2023-01-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_automotor_stock_alter_electrodomesticos_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automotor',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='automotor',
            name='shipping_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='electrodomesticos',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='electrodomesticos',
            name='shipping_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='shipping_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hogar',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hogar',
            name='shipping_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='indumentaria',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='indumentaria',
            name='shipping_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='perfumeria',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='perfumeria',
            name='shipping_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='shipping_cost',
            field=models.FloatField(),
        ),
    ]
